site_name: JSGameEngine
site_dir: docs
docs_dir: docs-src
theme:
  name: mkdocs
  highlightjs: true
  color_mode: auto
  user_color_mode_toggle: true
use_directory_urls: false

nav:
  - Home: index.md
  - About: about.md